services:
  - type: web
    name: pitch-downloader-api-simple
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt && python install_chromium.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --preload app:app
    healthCheckPath: /health
    envVars:
      - key: MAX_SLIDES
        value: 15
      - key: TIMEOUT
        value: 180
      - key: PYTHONUNBUFFERED
        value: 1

